# Generated by Django 5.2.7 on 2025-11-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                ("route_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("start_location", models.CharField(max_length=100)),
                ("end_location", models.CharField(max_length=100)),
            ],
        ),
    ]
