# Generated by Django 4.2.7 on 2025-11-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="route_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
