# Generated by Django 5.2.10 on 2026-01-21 16:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="route",
            name="distance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="route",
            name="duration",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="route",
            name="name",
            field=models.CharField(default="Unnamed Route", max_length=255),
        ),
        migrations.AddField(
            model_name="route",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="cities",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="route",
            name="polyline",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="route",
            name="end_location",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="route",
            name="start_location",
            field=models.CharField(default="", max_length=255),
        ),
    ]
