# Generated by Django 4.2.7 on 2025-11-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_alter_route_route_id"),
    ]

    operations = []
