# Generated by Django 5.2.10 on 2026-01-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_remove_route_cities_remove_route_polyline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="cities",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="polyline",
            field=models.TextField(blank=True, default=""),
        ),
    ]
