# Generated by Django 5.2.7 on 2025-11-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0003_auto_20251113_0622"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="cities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="route",
            name="polyline",
            field=models.TextField(blank=True, null=True),
        ),
    ]
